language: go

go:
  - 1.8
  - 1.9
  - tip

env:
  global:
    - DEP_VERSION="0.3.2"
    - CC_TEST_REPORTER_ID="1d904046788b6f68a50265a9d1fd89263709d30bd332156ac86ed3e55aca8a37"

before_install:
  # Download the binary to bin folder in $GOPATH
  - curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
  # Make the binary executable
  - chmod +x $GOPATH/bin/dep

install:
  - dep ensure -vendor-only

before_script:
  # coverage reporter
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  # gocov
  - go get -u github.com/axw/gocov/gocov
  - go install github.com/axw/gocov/gocov
  - chmod +x $GOPATH/bin/gocov

script:
  - go test -v -race -coverprofile=coverage.out -covermode=atomic

after_script:
  - $GOPATH/bin/gocov convert coverage.out > gocov.out
  - ./cc-test-reporter format-coverage -t gocov gocov.out
  - ./cc-test-reporter upload-coverage
